# This dictionary will help convert names of characters from first name only
# to first + last name.
character_dictionary = {
    'aeron' : 'aeron greyjoy',
    'aerson' : 'aeron greyjoy',
    'aemon' : 'maester aemon',
    'alliser' : 'alliser thorne',
    'alliser throne' : 'alliser thorne',
    'alliser thorn' : 'alliser thorne',
    'allister' : 'alliser thorne',
    'ayra' : 'arya stark',
    'arya' : 'arya stark',
    'baelish' : 'petyr baelish',
    'balon' : 'balon greyjoy',
    'barristan' : 'barristan selmy',
    'barriston' : 'barristan selmy',
    'beric' : 'beric dondarrion',
    'benjen' : 'benjen stark',
    'black walder' : 'walder rivers',
    'blackfish' : 'brynden tully',
    'brynden' : 'brynden tully',
    'bran' : 'bran stark',
    'brand' : 'bran stark',
    "bran's voice" : 'bran stark',
    'brann stark' : 'bran stark',
    'brienne' : 'brienne of tarth',
    'brinenne' : 'brienne of tarth',
    'bron' : 'bronn',
    'catelyin' : 'catelyn stark',
    'catelyn' : 'catelyn stark',
    'cersel' : 'cersei lannister',
    'cesei' : 'cersei lannister',
    'cersei' : 'cersei lannister',
    'cersie' : 'cersei lannister',
    'cersei baratheon' : 'cersei lannister',
    'cressen' : 'maester cressen',
    'daario' : 'daario naharis',
    'dario' : 'daario naharis',
    'darrio' : 'daario naharis',
    'daaerio' : 'daario naharis',
    'daeynerys' : 'daenerys targaryen',
    'dany' : 'daenerys targaryen',
    'danerys' : 'daenerys targaryen',
    'danaerys' : 'daenerys targaryen',
    'daenarys stormborn' : 'daenerys targaryen',
    'daenerys stormborn' : 'daenerys targaryen',
    'deanerys targarien' : 'daenerys targaryen',
    'daernys' : 'daenerys targaryen',
    'daenerys' : 'daenerys targaryen',
    'davis' : 'davos seaworth',
    'dav os' : 'davos seaworth',
    'davos' : 'davos seaworth',
    'dickon' : 'dickon stark',
    'doloroud edd' : 'eddison tollett',
    'dolorous edd' : 'eddison tollett',
    'dolrous edd' : 'eddison tollett',
    'doran' : 'doran martell',
    'elaria' : 'ellaria sand',
    'ellaria' : 'ellaria sand',
    'ellia' : 'ellaria sand',
    'ed' : 'eddison tollett',
    'eddark stark' : 'eddard stark',
    'edd' : 'eddison tollett',
    'eddision' : 'eddison tollett',
    'eddison' : 'eddison tollett',
    'edmure' : 'edmure tully',
    'ersei' : 'cersei lannister',
    'euron' : 'euron greyjoy',
    'gendry' : 'gendry rivers',
    'gold cloack' : 'gold cloak',
    'grand maester pyrcelle' : 'grand maester pycelle',
    'greyworm' : 'grey worm',
    'hizdahr' : 'hizdahr zo loraq',
    'hound' : 'sandor clegane',
    'illyrio' : 'illyrio mopatis',
    'jaqen' : "jaqen h'ghar",
    'jaime' : 'jaime lannister',
    'jamie lannister' : 'jaime lannister',
    'janos' : 'janos slynt',
    'janos slunt' : 'janos slynt',
    'jojen' : 'jojen reed',
    # 'john' : 'jon snow', jon snow or yohn royce?
    'jon' : 'jon snow',
    'jora' : 'jorah mormont',
    'jorah' : 'jorah mormont',
    'jeor' : 'jeor mormont',
    'jofffrey' : 'joffrey baratheon',
    'joffrey' : 'joffrey baratheon',
    'john royce' : 'yohn royce',
    'karl' : 'karl tanner',
    'kevan' : 'kevan lannister',
    'kraznys' : 'kraznys mo nakloz',
    'lady olenna' : 'olenna tyrell',
    'lady walda' : 'walda frey',
    'ladyc rane' : 'lady crane',
    'lancel' : 'lancel lannister',
    'littlefinger' : 'petyr baelish',
    'lollys' : 'lollys stokeworth',
    'lommy' : 'lommy greenhands',
    'loras' : 'loras tyrell',
    'lord bolton' : 'roose bolton',
    'lord royce' : 'yohn royce',
    'lothar' : 'lothar frey',
    'luwin' : 'maester luwin',
    'lysa' : 'lysa arryn',
    'lyanna' : 'lyanna mormont',
    'lyann' : 'lyanna mormont',
    'mace' : 'mace tyrell',
    'mance' : 'mance rayder',
    'margaery' : 'margaery tyrell',
    'martyn' : 'martyn lannister',
    'maester pycell' : 'maester pycelle',
    'meera' : 'meera reed',
    'melisdandre' : 'melisandre',
    'meryn' : 'meryn trant',
    'mosador' : 'mossador',
    'mountain' : 'gregor clegane',
    'moutian' : 'gregor clegane',
    'myrcella' : 'myrcella baratheon',
    'ned' : 'eddard stark',
    'ned stark' : 'eddard stark',
    'obara' : 'obara sand',
    'oberyn' : 'oberyn martell',
    'oleanna' : 'olenna',
    'olenna' : 'olenna tyrell',
    'olyvar' : 'olyvar frey',
    'petyr' : 'petyr baelish',
    'podrick' : 'podrick payne',
    'pyat pree' : 'pyatt pree',
    'pycell' : 'grand maester pycelle',
    'pyelle' : 'grand maester pycelle',
    'pycelle' : 'grand maester pycelle',
    'pyp' : 'pypar',
    'qhorin' : 'qhorin halfhand',
    'quaith' : 'quaithe',
    'quorin' : 'qhorin halfhand',
    'qyburn' : 'maester qyburn',
    'qyburns' : 'maester qyburn',
    'ramsay' : 'ramsay bolton',
    'ramsey' : 'ramsay bolton',
    'randyll' : 'randyll tarly',
    'rhakharo' : 'rakharo',
    'rhakaro' : 'rakharo',
    'rhaegar' : 'rhaegar targaryen',
    'robett' : 'robett glover',
    'rickard' : 'rickard karstark',
    'rickon' : 'rickon stark',
    'rikon' : 'rickon stark',
    'robin' : 'robin arryn',
    'robb' : 'robb stark',
    '-robb' : 'robb stark',
    'robert' : 'robert baratheon',
    'rodrik' : 'rodrik cassel',
    'roslin' : 'roslin frey',
    'roose' : 'roose bolton',
    'royce' : 'yohn royce',
    'roz' : 'ros',
    'salladhor' : 'salladhor saan',
    'sam' : 'samwell tarly',
    'same' : 'samwell tarly',
    'samwel tarly' : 'samwell tarly',
    'samwell' : 'samwell tarly',
    'sammy' : 'samwell tarly',
    'sandor' : 'sandor clegane',
    'sansa' : 'sansa stark',
    'selyse' : 'selyse baratheon',
    'ser dontos' : 'dontos hollard',
    'ser barristan' : 'barristan selmy',
    'ser jorah' : 'jorah mormont',
    'ser vance' : 'ser vance corbray',
    'ser rodrik' : 'rodrik cassel',
    'shireen' : 'shireen baratheon',
    'smalljon' : 'smalljon umber',
    'snsa' : 'sansa stark',
    'stannis' : 'stannis baratheon',
    'talisa' : 'talisa stark',
    'tanner' : 'karl tanner',
    'tansay' : 'tansy',
    'the hound' : 'sandor clegane',
    'theon' : 'theon greyjoy',
    'thoros' : 'thoros of myr',
    'tommen' : 'tommen baratheon',
    'tormund' : 'tormund giantsbane',
    'trion' : 'tyrion lannister',
    'trystane' : 'trystane martell',
    'tyene' : 'tyene sand',
    'twyin' : 'tywin lannister',
    'tycho' : 'tycho nestoris',
    'tyriom' : 'tyrion lannister',
    'tyrion' : 'tyrion lannister',
    'tyron' : 'tyrion lannister',
    'tywen' : 'tywin lannister',
    'tywin' : 'tywin lannister',
    'walda' : 'walda frey',
    'walder' : 'walder frey',
    'waldery frey' : 'walder frey',
    'wolkan' : 'maester wolkan',
    'varys' : 'lord varys',
    'viserys' : 'viserys targaryen',
    'yara' : 'yara greyjoy',
    'yarwick' : 'othell yarwick',
    'yarwyck' : 'othell yarwick',
    'young benjen' : 'benjen stark',
    'young hodor' : 'hodor',
    'yound lyanna' : 'lyanna stark',
    'yound ned' : 'eddard stark',
    'young rodrik' : 'rodrik cassel',
    'yohn' : 'yohn royce',
    'ytrion' : 'tyrion lannister'
}